server:
  port:

kafka:
  producer:
    topic: test
    servers: localhost:9092
    retries: 0
    batch:
      size: 4096
    linger: 1
    buffer:
      memory: 40960
  consumer:
    concurrency: 10
    group:
      id: test
    topic: test
    servsers: localhost:9092
    enable:
      auto:
        commit: true
    session:
      timeout: 20000
    auto:
      commit:
        interval: 100
      offeset:
        reset: latest



